apiVersion: apps/v1
kind: Deployment
metadata:
  name: xml-auditor-deploy
  labels:
    app: xml-auditor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xml-auditor
  template:
    metadata:
      labels:
        app: xml-auditor
    spec:
      containers:
      - name: xml-auditor-container
      image: ghcr.io/kchph3n0m/py-xml-auditor:latest
      ports:
      - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10