apiVersion: v1
kind: Service
metadata:
  name: xml-auditor-service
spec:
  selector:
    app: xml-auditor
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080